# Generated by Django 5.0 on 2024-01-25 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=300, null=True)),
                ('about', models.CharField(max_length=1000, null=True)),
                ('body', models.CharField(max_length=20000, null=True)),
                ('conclusion', models.CharField(max_length=1000, null=True)),
                ('images', models.ImageField(null=True, upload_to='blog_images/')),
                ('likes', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
                ('like', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_contents.blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('Comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_contents.comments')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_contents.blog')),
                ('replay_auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay', to='blog_contents.reply')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_contents.subcategory')),
            ],
        ),
    ]
