# Generated by Django 5.0 on 2024-01-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replay_auther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_contents.reply'),
        ),
    ]
