# Generated by Django 5.0 on 2024-02-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_contents', '0003_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_contents.categories'),
        ),
    ]
