# Generated by Django 5.0 on 2024-02-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_contents', '0004_remove_categories_sub_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_contents.subcategory'),
        ),
    ]
